# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Definition of production infra-related environment variables

variables:

  # Prod Environment
  environment: prod
  resource_group: rg-mlops-template-prod-001
  location: westeurope
  namespace: mlopsprodtmpl
  aml_workspace: aml$(namespace)
  storage_account: sa$(namespace)
  key_vault: kv$(namespace)
  application_insights: ai$(namespace)
  container_registry: cr$(namespace)
  service_connection_rg: conn-mlops-sub-infra
  service_connection_aml_ws: conn-mlops-aml-bsc-prod-tmpl
  gh_service_connection: mlops-v2-tabular