variables:

# Workspace settings
  ml_workspace_connection: Azure-ARM-Dev
  ml_workspace_name: main
  ml_workspace_rg: azureml-examples-rg

  version: python-sdk 

# Training Dataset settings
  training_dataset_name: uci-credit
  training_dataset_description: uci_credit
  training_dataset_local_path: data/
  training_dataset_path_on_datastore: data/
  training_dataset_type: local
  training_dataset_storage_url: 'https://azureaidemostorage.blob.core.windows.net/data/'

# Training pipeline settings

  # Training AzureML Environment name
  training_environment_name: credit-training

  # Training AzureML Environment conda yaml
  training_environment_conda_yaml: mlops/environments/train.yml

  # Name for the training pipeline
  training_pipeline_name: credit-training

  # Compute target for pipeline
  training_pipeline_target: cpu-cluster
  training_pipeline_target_min_nodes: 0
  training_pipeline_target_max_nodes: 4

  # Command to run for training, use azureml:dataset_name:version to reference a dataset
  training_command: 'train.py --data_path azureml:uci-credit:1'

  # Name under which the model will be registered
  model_name: credit-ci

# Batch pipeline settings

  # Batch AzureML Environment name
  batch_environment_name: credit-batch

  # Batch AzureML Environment conda yaml
  batch_environment_conda_yaml: mlops/environments/batch.yml

  # Name for the batch scoring pipeline
  batch_pipeline_name: credit-batch-scoring

  # Compute target for pipeline
  batch_pipeline_target: cpu-cluster

  # Input batch dataset
  batch_input_dataset_name: credit-batch-input

  # Output dataset with results
  batch_output_dataset_name: credit-batch-output
  batch_output_path_on_datastore: credit-batch-scoring-results/{run-id}
  batch_output_filename: results.csv

  # Parallelization settings
  batch_mini_batch_size: 8
  batch_error_threshold: 1
  batch_process_count_per_node: 1
  batch_node_count: 1
